// the dealer's log and the tv's toasts/announcer: what game.ts says happened.
// kept apart from gamePlay.ts (the dealer screen's own controls) since these
// strings are generated by game.ts, a plain logic file with no component of
// its own.
import type { Lang } from "./langs";

interface Plural {
  zero?: string;
  one?: string;
  two?: string;
  few?: string;
  many?: string;
  other: string;
}

export interface GameEventsDict {
  /** who rake and fees are owed to when the host hasn't named a house */
  defaultHouseName: string;
  created: string;
  satDownWithAmount: string;
  registered: string;
  satDownFlash: string;
  isInFlash: string;
  bustedLog: string;
  bustedFlash: string;
  bubbleLog: string;
  bubbleFlash: string;
  wins: string;
  unbustLog: string;
  dealKindIcm: string;
  dealKindChop: string;
  dealLog: string;
  dealFlash: string;
  knockoutLog: string;
  seatsDrawnLog: Plural;
  seatsDrawnFlash: string;
  movedLog: string;
  movedFlash: string;
  tableBrokeLog: string;
  tableBreakingFlash: string;
}

export const gameEvents: Record<Lang, GameEventsDict> = {
  en: {
    defaultHouseName: "The House",
    created: "Game created",
    satDownWithAmount: "{name} sat down ({amount})",
    registered: "{name} registered",
    satDownFlash: "{name} sat down",
    isInFlash: "{name} is in",
    bustedLog: "{name} busted in {place}",
    bustedFlash: "{name} is out in {place}",
    bubbleLog: "{name} went out on the bubble",
    bubbleFlash: "{name} is out on the bubble. Everyone left gets paid!",
    wins: "{name} wins!",
    unbustLog: "{name}'s bust undone",
    dealKindIcm: "ICM",
    dealKindChop: "chip chop",
    dealLog: "Deal ({kind}): {list}",
    dealFlash: "It's a deal! {names}",
    knockoutLog: "{by} knocked out {out}",
    seatsDrawnLog: { one: "Seats drawn: {n} players at {count} table", other: "Seats drawn: {n} players at {count} tables" },
    seatsDrawnFlash: "Seats are drawn",
    movedLog: "{name} moved to table {table}, seat {seat}",
    movedFlash: "{name}: table {table}, seat {seat}",
    tableBrokeLog: "Table {table} broke: {details}",
    tableBreakingFlash: "Table {table} is breaking",
  },
  zh: {
    defaultHouseName: "主办方",
    created: "牌局已创建",
    satDownWithAmount: "{name} 入座（{amount}）",
    registered: "{name} 已报名",
    satDownFlash: "{name} 入座",
    isInFlash: "{name} 已加入",
    bustedLog: "{name} 第 {place} 出局",
    bustedFlash: "{name} 第 {place} 出局",
    bubbleLog: "{name} 在泡沫圈出局",
    bubbleFlash: "{name} 在泡沫圈出局，其余玩家全部获得奖金！",
    wins: "{name} 获胜！",
    unbustLog: "已撤销 {name} 的出局",
    dealKindIcm: "ICM",
    dealKindChop: "筹码分配",
    dealLog: "分配（{kind}）：{list}",
    dealFlash: "达成分配协议！{names}",
    knockoutLog: "{by} 淘汰了 {out}",
    seatsDrawnLog: { other: "已抽座：{n} 名玩家，{count} 张桌" },
    seatsDrawnFlash: "座位已抽定",
    movedLog: "{name} 移至 {table} 号桌 {seat} 号座",
    movedFlash: "{name}：{table} 号桌 {seat} 号座",
    tableBrokeLog: "{table} 号桌解散：{details}",
    tableBreakingFlash: "{table} 号桌即将解散",
  },
  hi: {
    defaultHouseName: "हाउस",
    created: "गेम बनाया गया",
    satDownWithAmount: "{name} बैठे ({amount})",
    registered: "{name} ने रजिस्टर किया",
    satDownFlash: "{name} बैठे",
    isInFlash: "{name} शामिल हुए",
    bustedLog: "{name} {place} स्थान पर आउट हुए",
    bustedFlash: "{name} {place} स्थान पर आउट",
    bubbleLog: "{name} बबल पर आउट हुए",
    bubbleFlash: "{name} बबल पर आउट, बाकी सभी को भुगतान मिलेगा!",
    wins: "{name} जीत गए!",
    unbustLog: "{name} का आउट होना पूर्ववत किया गया",
    dealKindIcm: "ICM",
    dealKindChop: "चिप चॉप",
    dealLog: "डील ({kind}): {list}",
    dealFlash: "डील हो गई! {names}",
    knockoutLog: "{by} ने {out} को नॉकआउट किया",
    seatsDrawnLog: { one: "सीटें तय: {n} खिलाड़ी, {count} टेबल", other: "सीटें तय: {n} खिलाड़ी, {count} टेबल" },
    seatsDrawnFlash: "सीटें तय हो गईं",
    movedLog: "{name} टेबल {table}, सीट {seat} पर गए",
    movedFlash: "{name}: टेबल {table}, सीट {seat}",
    tableBrokeLog: "टेबल {table} बंद हुई: {details}",
    tableBreakingFlash: "टेबल {table} बंद हो रही है",
  },
  es: {
    defaultHouseName: "La Casa",
    created: "Partida creada",
    satDownWithAmount: "{name} se sentó ({amount})",
    registered: "{name} se inscribió",
    satDownFlash: "{name} se sentó",
    isInFlash: "{name} ya está",
    bustedLog: "{name} eliminado en el puesto {place}",
    bustedFlash: "{name} eliminado en el puesto {place}",
    bubbleLog: "{name} eliminado justo antes de la burbuja",
    bubbleFlash: "{name} eliminado en la burbuja. ¡Todos los que quedan cobran!",
    wins: "¡{name} gana!",
    unbustLog: "Se deshizo la eliminación de {name}",
    dealKindIcm: "ICM",
    dealKindChop: "reparto de fichas",
    dealLog: "Trato ({kind}): {list}",
    dealFlash: "¡Hay trato! {names}",
    knockoutLog: "{by} eliminó a {out}",
    seatsDrawnLog: { one: "Asientos sorteados: {n} jugadores en {count} mesa", other: "Asientos sorteados: {n} jugadores en {count} mesas" },
    seatsDrawnFlash: "Los asientos están sorteados",
    movedLog: "{name} se movió a la mesa {table}, asiento {seat}",
    movedFlash: "{name}: mesa {table}, asiento {seat}",
    tableBrokeLog: "Se cerró la mesa {table}: {details}",
    tableBreakingFlash: "La mesa {table} se está cerrando",
  },
  fr: {
    defaultHouseName: "La Maison",
    created: "Partie créée",
    satDownWithAmount: "{name} s'est assis ({amount})",
    registered: "{name} s'est inscrit",
    satDownFlash: "{name} s'est assis",
    isInFlash: "{name} est là",
    bustedLog: "{name} éliminé en {place} place",
    bustedFlash: "{name} éliminé en {place} place",
    bubbleLog: "{name} éliminé juste avant la bulle",
    bubbleFlash: "{name} éliminé sur la bulle. Tous les restants sont payés !",
    wins: "{name} gagne !",
    unbustLog: "Élimination de {name} annulée",
    dealKindIcm: "ICM",
    dealKindChop: "partage des jetons",
    dealLog: "Accord ({kind}) : {list}",
    dealFlash: "C'est un accord ! {names}",
    knockoutLog: "{by} a éliminé {out}",
    seatsDrawnLog: { one: "Places tirées : {n} joueurs sur {count} table", other: "Places tirées : {n} joueurs sur {count} tables" },
    seatsDrawnFlash: "Les places sont tirées",
    movedLog: "{name} déplacé à la table {table}, siège {seat}",
    movedFlash: "{name} : table {table}, siège {seat}",
    tableBrokeLog: "La table {table} est fermée : {details}",
    tableBreakingFlash: "La table {table} ferme",
  },
  ar: {
    defaultHouseName: "الجهة المنظمة",
    created: "تم إنشاء اللعبة",
    satDownWithAmount: "جلس {name} ({amount})",
    registered: "سجّل {name}",
    satDownFlash: "جلس {name}",
    isInFlash: "انضم {name}",
    bustedLog: "خرج {name} في المركز {place}",
    bustedFlash: "خرج {name} في المركز {place}",
    bubbleLog: "خرج {name} قبل مرحلة الفقاعة مباشرة",
    bubbleFlash: "خرج {name} في الفقاعة. جميع من تبقوا يحصلون على جائزة!",
    wins: "{name} يفوز!",
    unbustLog: "تم التراجع عن خروج {name}",
    dealKindIcm: "ICM",
    dealKindChop: "تقاسم الرقائق",
    dealLog: "اتفاق ({kind}): {list}",
    dealFlash: "تم الاتفاق! {names}",
    knockoutLog: "أقصى {by} اللاعب {out}",
    seatsDrawnLog: {
      zero: "تم توزيع المقاعد: {n} لاعبًا على {count} طاولة",
      one: "تم توزيع المقاعد: {n} لاعبًا على طاولة واحدة",
      two: "تم توزيع المقاعد: {n} لاعبًا على طاولتين",
      few: "تم توزيع المقاعد: {n} لاعبًا على {count} طاولات",
      many: "تم توزيع المقاعد: {n} لاعبًا على {count} طاولة",
      other: "تم توزيع المقاعد: {n} لاعبًا على {count} طاولة",
    },
    seatsDrawnFlash: "تم توزيع المقاعد",
    movedLog: "انتقل {name} إلى الطاولة {table}، المقعد {seat}",
    movedFlash: "{name}: الطاولة {table}، المقعد {seat}",
    tableBrokeLog: "أُغلقت الطاولة {table}: {details}",
    tableBreakingFlash: "الطاولة {table} تُغلق الآن",
  },
  bn: {
    defaultHouseName: "আয়োজক",
    created: "গেম তৈরি হয়েছে",
    satDownWithAmount: "{name} বসেছেন ({amount})",
    registered: "{name} নিবন্ধন করেছেন",
    satDownFlash: "{name} বসেছেন",
    isInFlash: "{name} যোগ দিয়েছেন",
    bustedLog: "{name} {place} স্থানে আউট হয়েছেন",
    bustedFlash: "{name} {place} স্থানে আউট",
    bubbleLog: "{name} বাবল পর্বে আউট হয়েছেন",
    bubbleFlash: "{name} বাবলে আউট, বাকি সবাই পুরস্কার পাবেন!",
    wins: "{name} জিতেছেন!",
    unbustLog: "{name} এর আউট বাতিল করা হয়েছে",
    dealKindIcm: "ICM",
    dealKindChop: "চিপ ভাগাভাগি",
    dealLog: "চুক্তি ({kind}): {list}",
    dealFlash: "চুক্তি হয়ে গেছে! {names}",
    knockoutLog: "{by}, {out} কে নকআউট করেছেন",
    seatsDrawnLog: { one: "আসন নির্ধারিত: {n} জন খেলোয়াড়, {count} টেবিল", other: "আসন নির্ধারিত: {n} জন খেলোয়াড়, {count} টেবিল" },
    seatsDrawnFlash: "আসন নির্ধারিত হয়েছে",
    movedLog: "{name} টেবিল {table}, আসন {seat} এ গেছেন",
    movedFlash: "{name}: টেবিল {table}, আসন {seat}",
    tableBrokeLog: "টেবিল {table} ভেঙে গেছে: {details}",
    tableBreakingFlash: "টেবিল {table} ভাঙা হচ্ছে",
  },
  pt: {
    defaultHouseName: "A Casa",
    created: "Jogo criado",
    satDownWithAmount: "{name} sentou-se ({amount})",
    registered: "{name} se inscreveu",
    satDownFlash: "{name} sentou-se",
    isInFlash: "{name} está dentro",
    bustedLog: "{name} eliminado em {place} lugar",
    bustedFlash: "{name} eliminado em {place} lugar",
    bubbleLog: "{name} eliminado bem antes da bolha",
    bubbleFlash: "{name} eliminado na bolha. Todos os que restam são pagos!",
    wins: "{name} vence!",
    unbustLog: "Eliminação de {name} desfeita",
    dealKindIcm: "ICM",
    dealKindChop: "divisão de fichas",
    dealLog: "Acordo ({kind}): {list}",
    dealFlash: "Fechou acordo! {names}",
    knockoutLog: "{by} eliminou {out}",
    seatsDrawnLog: { one: "Lugares sorteados: {n} jogadores em {count} mesa", other: "Lugares sorteados: {n} jogadores em {count} mesas" },
    seatsDrawnFlash: "Os lugares foram sorteados",
    movedLog: "{name} mudou para a mesa {table}, lugar {seat}",
    movedFlash: "{name}: mesa {table}, lugar {seat}",
    tableBrokeLog: "A mesa {table} fechou: {details}",
    tableBreakingFlash: "A mesa {table} está fechando",
  },
};
